//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_Functionality
    {
        public int Access_Func_ID { get; set; }
        public int Access_Level_ID { get; set; }
        public int Functionality_ID { get; set; }
    
        public virtual Access_Level Access_Level { get; set; }
        public virtual Functionality Functionality { get; set; }
    }
}
