//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Slot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking_Slot()
        {
            this.Employee_Slot = new HashSet<Employee_Slot>();
        }
    
        public int Booking_Slot_ID { get; set; }
        public System.DateTime Booking_Slot_Date { get; set; }
        public System.TimeSpan Booking_Slot_Start { get; set; }
        public System.TimeSpan Booking_Slot_End { get; set; }
        public string Booking_Slot_Venue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Slot> Employee_Slot { get; set; }
    }
}
