//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Challenge()
        {
            this.Challenge_Exercise_Plan = new HashSet<Challenge_Exercise_Plan>();
            this.Client_Challenge = new HashSet<Client_Challenge>();
        }
    
        public int Challenge_ID { get; set; }
        public System.DateTime Challenge_Start_Date { get; set; }
        public System.DateTime Challenge_End_Date { get; set; }
        public decimal Challenge_Amount { get; set; }
        public string Challenge_Prize { get; set; }
        public Nullable<int> Challenge_Status_ID { get; set; }
        public Nullable<int> Challenge_Type_ID { get; set; }
    
        public virtual Challenge_Status Challenge_Status { get; set; }
        public virtual Challenge_Type Challenge_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Challenge_Exercise_Plan> Challenge_Exercise_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Challenge> Client_Challenge { get; set; }
    }
}
