//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge_Exercise_Plan
    {
        public int Challenge_ID { get; set; }
        public int Exercise_Plan_ID { get; set; }
        public int Challenge_Month_Number { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual Exercise_Plan Exercise_Plan { get; set; }
    }
}
