//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Plan
    {
        public int Client_Plan_ID { get; set; }
        public int Client_ID { get; set; }
        public int Exercise_Plan_ID { get; set; }
        public string Plan_Reference_Number { get; set; }
        public Nullable<int> Payment_Status_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Exercise_Plan Exercise_Plan { get; set; }
        public virtual Payment_Status Payment_Status { get; set; }
    }
}
