//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Injury
    {
        public int Client_Injury_ID { get; set; }
        public int Client_ID { get; set; }
        public int Injury_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Injury Injury { get; set; }
    }
}
