//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Client_Challenge = new HashSet<Client_Challenge>();
            this.Client_Injury = new HashSet<Client_Injury>();
            this.Client_Plan = new HashSet<Client_Plan>();
            this.Payments = new HashSet<Payment>();
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public int Client_ID { get; set; }
        public string Client_Name { get; set; }
        public string Client_Surname { get; set; }
        public string Client_Contact { get; set; }
        public int Client_Height { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public decimal Subscription_Balance { get; set; }
        public Nullable<int> Client_Acc_Stat_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Gender_ID { get; set; }
    
        public virtual Client_Account_Status Client_Account_Status { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Challenge> Client_Challenge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Injury> Client_Injury { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Plan> Client_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
