//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee_Slot = new HashSet<Employee_Slot>();
        }
    
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Surname { get; set; }
        public string Employee_Contact { get; set; }
        public System.DateTime Employee_Birth_Date { get; set; }
        public Nullable<int> Employee_Type_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Gender_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Slot> Employee_Slot { get; set; }
        public virtual Employee_Type Employee_Type { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual User User { get; set; }
    }
}
