//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise_Plan_Day
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exercise_Plan_Day()
        {
            this.Day_Workout = new HashSet<Day_Workout>();
        }
    
        public int Exercise_Plan_Day_ID { get; set; }
        public int Exercise_Plan_ID { get; set; }
        public int Day_ID { get; set; }
    
        public virtual Day Day { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Day_Workout> Day_Workout { get; set; }
        public virtual Exercise_Plan Exercise_Plan { get; set; }
    }
}
