//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exercise()
        {
            this.Exercise_Set = new HashSet<Exercise_Set>();
        }
    
        public int Exercise_ID { get; set; }
        public string Exercise_Name { get; set; }
        public string Exercise_Description { get; set; }
        public int Exercise_Type_ID { get; set; }
        public int Exercise_Body_Type_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exercise_Set> Exercise_Set { get; set; }
        public virtual Exercise_Type Exercise_Type { get; set; }
        public virtual Exercise_Body_Type Exercise_Body_Type { get; set; }
    }
}
