//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JessterFITdbEntities : DbContext
    {
        public JessterFITdbEntities()
            : base("name=JessterFITdbEntities")
        {
            base.Configuration.ProxyCreationEnabled = false;
            base.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access_Functionality> Access_Functionality { get; set; }
        public virtual DbSet<Access_Level> Access_Level { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Booking_Slot> Booking_Slot { get; set; }
        public virtual DbSet<Booking_Status> Booking_Status { get; set; }
        public virtual DbSet<Booking_Type> Booking_Type { get; set; }
        public virtual DbSet<Challenge> Challenges { get; set; }
        public virtual DbSet<Challenge_Exercise_Plan> Challenge_Exercise_Plan { get; set; }
        public virtual DbSet<Challenge_Pay_Status> Challenge_Pay_Status { get; set; }
        public virtual DbSet<Challenge_Payment> Challenge_Payment { get; set; }
        public virtual DbSet<Challenge_Status> Challenge_Status { get; set; }
        public virtual DbSet<Challenge_Type> Challenge_Type { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Client_Account_Status> Client_Account_Status { get; set; }
        public virtual DbSet<Client_Challenge> Client_Challenge { get; set; }
        public virtual DbSet<Client_Injury> Client_Injury { get; set; }
        public virtual DbSet<Client_Plan> Client_Plan { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<Day_Workout> Day_Workout { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Slot> Employee_Slot { get; set; }
        public virtual DbSet<Employee_Type> Employee_Type { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<Exercise_Body_Type> Exercise_Body_Type { get; set; }
        public virtual DbSet<Exercise_Plan> Exercise_Plan { get; set; }
        public virtual DbSet<Exercise_Plan_Day> Exercise_Plan_Day { get; set; }
        public virtual DbSet<Exercise_Plan_Type> Exercise_Plan_Type { get; set; }
        public virtual DbSet<Exercise_Set> Exercise_Set { get; set; }
        public virtual DbSet<Exercise_Type> Exercise_Type { get; set; }
        public virtual DbSet<Functionality> Functionalities { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Injury> Injuries { get; set; }
        public virtual DbSet<Injury_Type> Injury_Type { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Payment_Status> Payment_Status { get; set; }
        public virtual DbSet<Set> Sets { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<Subscription_Exercise_Plan> Subscription_Exercise_Plan { get; set; }
        public virtual DbSet<Subscription_Payment> Subscription_Payment { get; set; }
        public virtual DbSet<Subscription_Status> Subscription_Status { get; set; }
        public virtual DbSet<Subscription_Type> Subscription_Type { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Status> User_Status { get; set; }
        public virtual DbSet<Weight> Weights { get; set; }
        public virtual DbSet<Workout> Workouts { get; set; }
        public virtual DbSet<Workout_Set> Workout_Set { get; set; }
    }
}
