//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_ID { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public decimal Payment_Amount { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Exercise_Plan_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Exercise_Plan Exercise_Plan { get; set; }
    }
}
