//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscription()
        {
            this.Subscription_Payment = new HashSet<Subscription_Payment>();
            this.Subscription_Exercise_Plan = new HashSet<Subscription_Exercise_Plan>();
        }
    
        public int Subscription_ID { get; set; }
        public System.DateTime Subscription_Start_Date { get; set; }
        public string Sub_Reference_Number { get; set; }
        public System.DateTime Subscription_End_Date { get; set; }
        public Nullable<int> Sub_Status_ID { get; set; }
        public Nullable<int> Sub_Type_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Booking_ID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Client Client { get; set; }
        public virtual Subscription_Status Subscription_Status { get; set; }
        public virtual Subscription_Type Subscription_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription_Payment> Subscription_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription_Exercise_Plan> Subscription_Exercise_Plan { get; set; }
    }
}
