//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription_Payment
    {
        public int Sub_Pay_ID { get; set; }
        public System.DateTime Sub_Pay_Date { get; set; }
        public decimal Sub_Pay_Amount { get; set; }
        public int Subscription_ID { get; set; }
    
        public virtual Subscription Subscription { get; set; }
    }
}
