//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weight
    {
        public int Weight_ID { get; set; }
        public decimal Weight_Amount { get; set; }
        public Nullable<int> Booking_ID { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
