//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JessterFITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workout_Set
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workout_Set()
        {
            this.Day_Workout = new HashSet<Day_Workout>();
        }
    
        public int Workout_Set_ID { get; set; }
        public int Workout_ID { get; set; }
        public int Exercise_Set_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Day_Workout> Day_Workout { get; set; }
        public virtual Exercise_Set Exercise_Set { get; set; }
        public virtual Workout Workout { get; set; }
    }
}
